baseurl = "/"
title = "DevOps Notes..."
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "toko"
googleAnalytics = "UA-85259301-1"

[menu]

  [[menu.main]]
    name = "setup"
    weight = 10
    url = "/setup"

  [[menu.main]]
    name = "library"
    weight = 4
    url = "/library"

  [[menu.main]]
    name = "cheats"
    weight = 1
    url = "/cheats"


[params]
  GithubID = "tokozedg"
  TwitterID = "Zedginidze"
  LinkedInID = "tokozedg"
  GoogleplusID = "101511740319661471581"
  KeyBase = "toko"
  homeDir = ""
